### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by TheConnMan**
Add additional UI themes which can be toggled between.

### CODE REVIEW

**Comment by TheConnMan** [comment]
Themes are from http://semantic-ui-forest.com/themes/.


image
image
image
image

**Comment by TheConnMan** [comment]
My favorites are Yeti, Superhero, and Lumen. I'd be down for picking 4 or so and removing the rest, no need to have choice overload.

**Comment by SirZach** [comment]
If you wouldn't mind including Paper in there that'd be my only request. Great find!

**Comment by TheConnMan** [comment]
@Createor Any others you like? Otherwise we'll reduce the choices to Default, Paper, Lumen, Superhero, and Yeti.

**Comment by Createor** [comment]
Throw United in there and I'm set :)

**Pull request merged**
